# Generated by Django 4.0.3 on 2022-04-06 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_videoart'),
    ]

    operations = [
        migrations.CreateModel(
            name='performances',
            fields=[
                ('performanceId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.TextField()),
                ('performlink', models.URLField()),
                ('socialLink', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artgallery.category')),
            ],
        ),
    ]
